# Ensembles

In [2]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score
from sklearn.externals.six import StringIO
import subprocess

c:\users\madhumita.ganesan\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [3]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score
from sklearn.externals.six import StringIO
import subprocess

In [11]:
np.random.seed(1234)

mod1=np.random.rand(5000)
mod2 = np.random.rand(5000)
mod3 = np.random.rand(5000)
mod4 = np.random.rand(5000)
mod5 = np.random.rand(5000)

In [12]:

# each model independently predicts 1 (the "correct response") if random number was at least 0.3
preds1 = np.where(mod1 > 0.3, 1, 0)
preds2 = np.where(mod2 > 0.3, 1, 0)
preds3 = np.where(mod3 > 0.3, 1, 0)
preds4 = np.where(mod4 > 0.3, 1, 0)
preds5 = np.where(mod5 > 0.3, 1, 0)

In [13]:
print(preds1[:20])
print(preds2[:20])
print(preds3[:20])
print(preds4[:20])
print(preds5[:20])

[0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1]
[1 1 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0 1 1]
[1 1 1 1 0 1 0 1 1 0 1 0 1 1 1 0 0 0 0 1]
[1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1]
[1 0 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 0 1 1]


In [15]:
# average the predictions and then round to 0 or 1
ensemble_preds = np.round((preds1 + preds2 + preds3 + preds4 + preds5)/5.0).astype(int)

# print the ensemble's first 20 predictions
print(ensemble_preds[:20])

[1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 1 0 1 1]


In [16]:
# how accurate was each individual model?
print(preds1.mean())
print(preds2.mean())
print(preds3.mean())
print(preds4.mean())
print(preds5.mean())

0.6988
0.6988
0.7
0.7014
0.6982


In [17]:
# how accurate was the ensemble?
print(ensemble_preds.mean())

0.8364


In [18]:
### Bagging

In [19]:
# set a seed for reproducibility
np.random.seed(20)

# create an array of 1 through 30
nums = np.arange(1, 30)
print("The original array:",nums)

# sample that array 15 times with replacement
print("The 15 samples:",np.random.choice(a=nums, size=15, replace=True))

The original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
The 15 samples: [ 4 27 16 29 27 10 21 12 23  8  3  1 23  9 22]


In [20]:
### Manually implementing Bagged regression Trees

np.random.seed(1234)

samples=[np.random.choice(a=X_train.shape[0],size=X_train.shape[0],replace=True) for _ in range(1,11)]

NameError: name 'X_train' is not defined